### ISSUE TITLE
version on github/galaxy ansible

### ISSUE THREAD

**Issue by klemenkobetic** [zenoamaro/ansible-postgresql#4]
Version on galaxy-ansible is not up-to-date with the version on githhub! Please update!

**Comment by zenoamaro** [comment]
Sorry for that, will update it soon!

**Comment by zenoamaro** [comment]
It appears that the roles are stuck in re-import since the last update (oops).

I've opened a ticket on the galaxy, this should be solved soon.

I'm keeping this open in the mean time.

**Comment by zenoamaro** [comment]
Hi, @klemenkobetic, 0.1.2 should be available on galaxy now.
