### ISSUE TITLE
is not a database cluster directory

### ISSUE THREAD

**Issue by klemenkobetic** [zenoamaro/ansible-postgresql#5]
using what is currently on the repository with default box config fails with :

NOTIFIED: [zenoamaro.postgresql | restart postgresql] ************************* 
failed: [test] => {"failed": true}
msg:  * Stopping PostgreSQL 9.4 database server
   ...done.
 * Starting PostgreSQL 9.4 database server
 * Error: could not exec /usr/lib/postgresql/9.4/bin/pg_ctl /usr/lib/postgresql/9.4/bin/pg_ctl start -D /var/lib/postgresql/9.4/main -l /var/log/postgresql/postgresql-9.4-main.log -s -o  -c config_file="/etc/postgresql/9.4/main/postgresql.conf" : 
   ...fail!
FATAL: all hosts have already failed -- aborting

all default configuration from box.yml

later inspection shows :

postgres@vagrant-ubuntu-trusty-64:~$ /usr/lib/postgresql/9.4/bin/pg_ctl start -D /var/lib/postgresql/9.4/main -c
pg_ctl: directory "/var/lib/postgresql/9.4/main" is not a database cluster directory

so by running "initdb -D /var/lib/postgresql/9.4/main" it works!

also, /var/lib/postgresql/9.4/main should only have 700 rights (if google is correct)

**Comment by zenoamaro** [comment]
Mmh. I'm not able to reproduce this with any of the test machines, nor the boxed install.

I've pushed a new release which should be on the galaxy soon. Try that when it's published, and let me know.

**Comment by klemenkobetic** [comment]
Found the problem and the solution: 

The problem:
Combination of Ansible + Vagrant
Host computer is using differente locale then ubuntu14 box.

The solution :
Install also locale that the host computer is using
or
Use en_US.UTF-8 locale (ubuntu box default)

**Comment by zenoamaro** [comment]
Okay, I'll have to do a few tests to see why the locale is being used to create the cluster.

What locale are you on?

**Comment by raj45** [comment]
The solution was to execute these commands inside the box, before adding the ansible-postgresql role and running <code>vagrant provision</code>:
<pre>export LANGUAGE="en_US.UTF-8"
echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale</pre>

I will also post this solution in the original issue ([Add PostgreSQL support?](https://github.com/hashbangcode/vlad/issues/239)) at the Vlad project, since it probably should be included in the Vlad Playbook.

**Comment by raj45** [comment]
This recipe should work:
<pre>mkdir vlad_postgres
cd vlad_postgres/
git clone https://github.com/hashbangcode/vlad.git
# add custom role postgresql
git clone https://github.com/zenoamaro/ansible-postgresql.git
mv ansible-postgresql/ vlad_custom
cp vlad/vlad/example.settings.yml vlad/vlad/settings.yml
cd vlad
vagrant up
vagrant ssh
# run these commands to insert missing locale settings
export LANGUAGE="en_US.UTF-8"
echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale
# exit the box and udpdate settings
# change boxname to "boxname: vladtest" and add "custom_provision: true"
vi vlad/settings.yml
vagrant provision
vagrant ssh
# check postgresql is installed
psql</pre>

**Comment by zenoamaro** [comment]
@raj45 can you try branch `locale-generation` (b4eef0d92f7f8f7743fc92c4336df61775e4b981) and see if this solves your issue as well as your solution?

**Comment by zenoamaro** [comment]
@raj45, pinging to see if the locale-generation branch solves your issue, so that I can merge it. Thanks,

**Comment by raj45** [comment]
I can't remember if I tested it, and have since stopped experimenting with postgresql, so I can't really help, sorry.

**Comment by zenoamaro** [comment]
Thanks anyway! I'll integrate this feature separately from this issue.
